### ISSUE TITLE
Possible mistake in sanity check function

### ISSUE THREAD

**Issue by dbalabka** [ethen8181/machine-learning#12]
`z` variable isn't used in interval calculation:
```python
def sanity_check(size1, size2, significance = 0.05):
    n = size1 + size2
    confidence = 1 - significance
    z = stats.norm.ppf(confidence + significance / 2)
    confint = n * 0.5 + np.array([-1, 1]) * np.sqrt(n * 0.5 * 0.5)
    return confint
```

Source: http://ethen8181.github.io/machine-learning/ab_tests/frequentist_ab_test.html#Sanity-Check

**Comment by ethen8181** [comment]
Thanks for pointing this out, I've added the multiplication of the `z` variable in the confidence interval calculation with the latest commit. https://github.com/ethen8181/machine-learning/commit/39d5d02a79840e8c694bedb427c575d0bfe7ed5f

**Comment by ethen8181** [comment]
closing this as it's resolved, feel free re-open if you feel that's not the case.
